// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apikeys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countApiKeyByUserID = `-- name: CountApiKeyByUserID :one
SELECT
    COUNT(*)
FROM
    apikeys
WHERE
    apikeys.user_id = $1 :: uuid
`

func (q *Queries) CountApiKeyByUserID(ctx context.Context, userid pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApiKeyByUserID, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserIDByApiKeyHash = `-- name: GetUserIDByApiKeyHash :one
SELECT
    user_id
FROM
    apikeys
WHERE
    apikeys.key_hash = $1
    AND (
        apikeys.expired_at = 'infinity'
        OR apikeys.expired_at > now()
    )
`

func (q *Queries) GetUserIDByApiKeyHash(ctx context.Context, keyHash string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserIDByApiKeyHash, keyHash)
	var user_id pgtype.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const insertApiKey = `-- name: InsertApiKey :exec
INSERT INTO
    apikeys (
        apikey_id,
        key_hash,
        user_id,
        plain_suffix,
        expired_at
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5
    )
`

type InsertApiKeyParams struct {
	ApikeyID       pgtype.UUID        `json:"apikey_id"`
	KeyHash        string             `json:"key_hash"`
	UserID         pgtype.UUID        `json:"user_id"`
	KeyPlainSuffix string             `json:"key_plain_suffix"`
	ExpiredAt      pgtype.Timestamptz `json:"expired_at"`
}

func (q *Queries) InsertApiKey(ctx context.Context, arg InsertApiKeyParams) error {
	_, err := q.db.Exec(ctx, insertApiKey,
		arg.ApikeyID,
		arg.KeyHash,
		arg.UserID,
		arg.KeyPlainSuffix,
		arg.ExpiredAt,
	)
	return err
}

const listApiKeysByUserID = `-- name: ListApiKeysByUserID :many
SELECT
    apikey_id,
    plain_suffix,
    _created_at,
    expired_at
FROM
    apikeys
WHERE
    apikeys.user_id = $1 :: uuid
`

type ListApiKeysByUserIDRow struct {
	ApikeyID    pgtype.UUID        `json:"apikey_id"`
	PlainSuffix string             `json:"plain_suffix"`
	CreatedAt   pgtype.Timestamptz `json:"_created_at"`
	ExpiredAt   pgtype.Timestamptz `json:"expired_at"`
}

func (q *Queries) ListApiKeysByUserID(ctx context.Context, userid pgtype.UUID) ([]ListApiKeysByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listApiKeysByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApiKeysByUserIDRow{}
	for rows.Next() {
		var i ListApiKeysByUserIDRow
		if err := rows.Scan(
			&i.ApikeyID,
			&i.PlainSuffix,
			&i.CreatedAt,
			&i.ExpiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
