// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contacts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertContact = `-- name: InsertContact :exec
INSERT INTO
    contacts (
        contact_id,
        name,
        email,
        phone,
        content,
        ip_address,
        user_agent
    )
VALUES
    (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
`

type InsertContactParams struct {
	ContactID pgtype.UUID `json:"contact_id"`
	Name      string      `json:"name"`
	Email     string      `json:"email"`
	Phone     pgtype.Text `json:"phone"`
	Content   string      `json:"content"`
	IpAddress string      `json:"ip_address"`
	UserAgent string      `json:"user_agent"`
}

func (q *Queries) InsertContact(ctx context.Context, arg InsertContactParams) error {
	_, err := q.db.Exec(ctx, insertContact,
		arg.ContactID,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Content,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}
