// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCourseById = `-- name: GetCourseById :one
SELECT
    courses.course_id,
    courses.title,
    courses.description,
    courses.slug,
    courses.tags,
    courses.publish_status,
    courses.category_id,
    categories.name AS category_name,
    courses.published_at,
    courses.author_id,
    authors.name AS author_name,
    courses.visibility,
    json_agg(
        json_build_object(
            'course_section_id',
            sections.course_section_id,
            'title',
            sections.title,
            'description',
            sections.description,
            'topics',
            sections.topics
        )
        ORDER BY
            sections."index" ASC
    ) AS sections
FROM
    courses
    JOIN categories USING (category_id)
    JOIN authors USING (author_id)
    JOIN (
        SELECT
            course_sections.course_id,
            course_sections.course_section_id,
            course_sections.title,
            course_sections.description,
            course_sections."index",
            json_agg(
                json_build_object(
                    'course_section_topic_id',
                    course_section_topic_id,
                    'title',
                    course_section_topics.title,
                    'description',
                    course_section_topics.description,
                    'content',
                    course_section_topics.content
                )
                ORDER BY
                    course_section_topics."index" ASC
            ) AS topics
        FROM
            course_sections
            JOIN course_section_topics USING (course_section_id)
        GROUP BY
            course_sections.course_id,
            course_sections.course_section_id
    ) AS sections USING (course_id)
WHERE
    courses.course_id = $1 :: uuid
GROUP BY
    courses.course_id,
    courses.title,
    courses.description,
    courses.slug,
    courses.tags,
    courses.publish_status,
    courses.category_id,
    categories.name,
    courses.published_at,
    courses.author_id,
    authors.name,
    courses.visibility
`

type GetCourseByIdRow struct {
	CourseID      pgtype.UUID        `json:"course_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Slug          string             `json:"slug"`
	Tags          []byte             `json:"tags"`
	PublishStatus string             `json:"publish_status"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	CategoryName  string             `json:"category_name"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AuthorID      pgtype.UUID        `json:"author_id"`
	AuthorName    string             `json:"author_name"`
	Visibility    string             `json:"visibility"`
	Sections      []byte             `json:"sections"`
}

func (q *Queries) GetCourseById(ctx context.Context, courseid pgtype.UUID) (GetCourseByIdRow, error) {
	row := q.db.QueryRow(ctx, getCourseById, courseid)
	var i GetCourseByIdRow
	err := row.Scan(
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Tags,
		&i.PublishStatus,
		&i.CategoryID,
		&i.CategoryName,
		&i.PublishedAt,
		&i.AuthorID,
		&i.AuthorName,
		&i.Visibility,
		&i.Sections,
	)
	return i, err
}

const getCourses = `-- name: GetCourses :many
SELECT
    course_id AS "courseId",
    title
FROM
    courses
WHERE
    (
        courses.publish_status = 'published'
        AND courses.visibility IN ('public', 'paid')
    )
    AND (
        $1 :: uuid IS NULL
        OR course_id > $1
    )
    AND (
        NULLIF($2 :: text, '') IS NULL
        OR title LIKE '%' || $2 || '%'
        OR description LIKE '%' || $2 || '%'
    )
ORDER BY
    course_id
LIMIT
    $3
`

type GetCoursesParams struct {
	Cursor  pgtype.UUID `json:"cursor"`
	Keyword string      `json:"keyword"`
	Size    int32       `json:"size"`
}

type GetCoursesRow struct {
	CourseId pgtype.UUID `json:"courseId"`
	Title    string      `json:"title"`
}

func (q *Queries) GetCourses(ctx context.Context, arg GetCoursesParams) ([]GetCoursesRow, error) {
	rows, err := q.db.Query(ctx, getCourses, arg.Cursor, arg.Keyword, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCoursesRow{}
	for rows.Next() {
		var i GetCoursesRow
		if err := rows.Scan(&i.CourseId, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProgressByUserIdAndCourseId = `-- name: GetProgressByUserIdAndCourseId :many
SELECT
    tp.course_section_topic_id,
    tp.user_id,
    tp.status,
    cs."index" AS section_index,
    cst."index" AS topic_index
FROM
    topic_progresses tp
    JOIN course_section_topics cst ON tp.course_section_topic_id = cst.course_section_topic_id
    JOIN course_sections cs ON cst.course_section_id = cs.course_section_id
WHERE
    tp.user_id = $1 :: uuid
    AND tp.course_id = $2 :: uuid
`

type GetProgressByUserIdAndCourseIdParams struct {
	Userid   pgtype.UUID `json:"userid"`
	Courseid pgtype.UUID `json:"courseid"`
}

type GetProgressByUserIdAndCourseIdRow struct {
	CourseSectionTopicID pgtype.UUID `json:"course_section_topic_id"`
	UserID               pgtype.UUID `json:"user_id"`
	Status               string      `json:"status"`
	SectionIndex         int16       `json:"section_index"`
	TopicIndex           int16       `json:"topic_index"`
}

func (q *Queries) GetProgressByUserIdAndCourseId(ctx context.Context, arg GetProgressByUserIdAndCourseIdParams) ([]GetProgressByUserIdAndCourseIdRow, error) {
	rows, err := q.db.Query(ctx, getProgressByUserIdAndCourseId, arg.Userid, arg.Courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProgressByUserIdAndCourseIdRow{}
	for rows.Next() {
		var i GetProgressByUserIdAndCourseIdRow
		if err := rows.Scan(
			&i.CourseSectionTopicID,
			&i.UserID,
			&i.Status,
			&i.SectionIndex,
			&i.TopicIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicDetail = `-- name: GetTopicDetail :one
SELECT
    courses.course_id AS "courseId",
    course_sections.course_section_id AS "sectionId",
    course_section_topics.course_section_topic_id as "topicId",
    course_section_topics.title,
    course_section_topics.description,
    course_section_topics.content
FROM
    course_section_topics
    JOIN course_sections USING (course_section_id)
    JOIN courses ON courses.course_id = course_sections.course_id
WHERE
    course_section_topic_id = $1 :: uuid
    AND course_sections.course_section_id = $2 :: uuid
    AND course_sections.course_id = $3 :: uuid
    AND (
        courses.publish_status = 'published'
        OR (
            $4 :: uuid IS NOT NULL
            AND courses.author_id = $4 :: uuid
        )
    )
`

type GetTopicDetailParams struct {
	TopicID   pgtype.UUID `json:"topic_id"`
	SectionID pgtype.UUID `json:"section_id"`
	CourseID  pgtype.UUID `json:"course_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type GetTopicDetailRow struct {
	CourseId    pgtype.UUID `json:"courseId"`
	SectionId   pgtype.UUID `json:"sectionId"`
	TopicId     pgtype.UUID `json:"topicId"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Content     string      `json:"content"`
}

func (q *Queries) GetTopicDetail(ctx context.Context, arg GetTopicDetailParams) (GetTopicDetailRow, error) {
	row := q.db.QueryRow(ctx, getTopicDetail,
		arg.TopicID,
		arg.SectionID,
		arg.CourseID,
		arg.UserID,
	)
	var i GetTopicDetailRow
	err := row.Scan(
		&i.CourseId,
		&i.SectionId,
		&i.TopicId,
		&i.Title,
		&i.Description,
		&i.Content,
	)
	return i, err
}
