// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCourseSectionTopicsByCourseID = `-- name: DeleteCourseSectionTopicsByCourseID :exec
DELETE FROM course_section_topics
WHERE course_id = $1 :: UUID
`

func (q *Queries) DeleteCourseSectionTopicsByCourseID(ctx context.Context, courseid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseSectionTopicsByCourseID, courseid)
	return err
}

const deleteCourseSectionsByCourseID = `-- name: DeleteCourseSectionsByCourseID :exec
DELETE FROM course_sections
WHERE course_id = $1 :: UUID
`

func (q *Queries) DeleteCourseSectionsByCourseID(ctx context.Context, courseid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCourseSectionsByCourseID, courseid)
	return err
}

const getAuthorByUserID = `-- name: GetAuthorByUserID :one
SELECT
    authors.author_id,
    authors.name,
    authors.slug,
    authors.profile
FROM
    authors
    JOIN user_authors USING (author_id)
WHERE
    user_authors.user_id = $1 :: UUID
ORDER BY
    user_authors._created_at ASC
LIMIT 1
`

type GetAuthorByUserIDRow struct {
	AuthorID pgtype.UUID `json:"author_id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	Profile  string      `json:"profile"`
}

func (q *Queries) GetAuthorByUserID(ctx context.Context, userid pgtype.UUID) (GetAuthorByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getAuthorByUserID, userid)
	var i GetAuthorByUserIDRow
	err := row.Scan(
		&i.AuthorID,
		&i.Name,
		&i.Slug,
		&i.Profile,
	)
	return i, err
}

const getCategoryByPath = `-- name: GetCategoryByPath :one
SELECT
    category_id,
    name
FROM
    categories
WHERE
    path = $1 :: ltree
`

type GetCategoryByPathRow struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Name       string      `json:"name"`
}

func (q *Queries) GetCategoryByPath(ctx context.Context, path string) (GetCategoryByPathRow, error) {
	row := q.db.QueryRow(ctx, getCategoryByPath, path)
	var i GetCategoryByPathRow
	err := row.Scan(&i.CategoryID, &i.Name)
	return i, err
}

const getCourseById = `-- name: GetCourseById :one
SELECT
    courses.course_id,
    courses.title,
    courses.description,
    courses.slug,
    courses.tags,
    courses.publish_status,
    courses.category_id,
    categories.name AS category_name,
    courses.published_at,
    courses.author_id,
    authors.name AS author_name,
    courses.visibility,
    json_agg(
        json_build_object(
            'course_section_id',
            sections.course_section_id,
            'title',
            sections.title,
            'description',
            sections.description,
            'topics',
            sections.topics
        )
        ORDER BY
            sections."index" ASC
    ) AS sections
FROM
    courses
    JOIN categories USING (category_id)
    JOIN authors USING (author_id)
    JOIN (
        SELECT
            course_sections.course_id,
            course_sections.course_section_id,
            course_sections.title,
            course_sections.description,
            course_sections."index",
            json_agg(
                json_build_object(
                    'course_section_topic_id',
                    course_section_topic_id,
                    'title',
                    course_section_topics.title,
                    'description',
                    course_section_topics.description,
                    'content',
                    course_section_topics.content
                )
                ORDER BY
                    course_section_topics."index" ASC
            ) AS topics
        FROM
            course_sections
            JOIN course_section_topics USING (course_section_id)
        GROUP BY
            course_sections.course_id,
            course_sections.course_section_id
    ) AS sections USING (course_id)
WHERE
    courses.course_id = $1 :: uuid
GROUP BY
    courses.course_id,
    courses.title,
    courses.description,
    courses.slug,
    courses.tags,
    courses.publish_status,
    courses.category_id,
    categories.name,
    courses.published_at,
    courses.author_id,
    authors.name,
    courses.visibility
`

type GetCourseByIdRow struct {
	CourseID      pgtype.UUID        `json:"course_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Slug          string             `json:"slug"`
	Tags          []byte             `json:"tags"`
	PublishStatus string             `json:"publish_status"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	CategoryName  string             `json:"category_name"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AuthorID      pgtype.UUID        `json:"author_id"`
	AuthorName    string             `json:"author_name"`
	Visibility    string             `json:"visibility"`
	Sections      []byte             `json:"sections"`
}

func (q *Queries) GetCourseById(ctx context.Context, courseid pgtype.UUID) (GetCourseByIdRow, error) {
	row := q.db.QueryRow(ctx, getCourseById, courseid)
	var i GetCourseByIdRow
	err := row.Scan(
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Tags,
		&i.PublishStatus,
		&i.CategoryID,
		&i.CategoryName,
		&i.PublishedAt,
		&i.AuthorID,
		&i.AuthorName,
		&i.Visibility,
		&i.Sections,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
WITH
    target_course AS (
        SELECT courses.course_id
        FROM courses
            JOIN authors USING (author_id)
        WHERE courses.slug = $1
            AND authors.slug = $2
    ),
    section_agg AS (
        SELECT
            sections.course_id,
            sections.course_section_id,
            sections.title,
            sections.description,
            sections.index,
            COALESCE(
                jsonb_agg(
                    jsonb_build_object(
                        'course_section_topic_id', topics.course_section_topic_id,
                        'title', topics.title,
                        'description', topics.description,
                        'content', topics."content"
                    )
                    ORDER BY topics.index
                ) FILTER (WHERE topics.course_section_topic_id IS NOT NULL),
                '[]'::jsonb
            ) AS topics
        FROM
            course_sections AS sections
            LEFT JOIN course_section_topics AS topics
                ON topics.course_section_id = sections.course_section_id
        WHERE
            sections.course_id = (SELECT course_id FROM target_course)
        GROUP BY
            sections.course_id,
            sections.course_section_id
    )
SELECT
    courses.course_id,
    courses.title,
    courses.description,
    courses.slug,
    courses.tags,
    courses.publish_status,
    courses.category_id,
    categories.name AS category_name,
    courses.published_at,
    courses.author_id,
    authors.name AS author_name,
    authors.slug AS author_slug,
    courses.visibility,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'course_section_id', section_agg.course_section_id,
                'title', section_agg.title,
                'description', section_agg.description,
                'topics', section_agg.topics
            )
            ORDER BY section_agg.index
        ) FILTER (WHERE section_agg.course_section_id IS NOT NULL),
        '[]'::jsonb
    ) :: jsonb AS sections
FROM
    courses
    JOIN categories USING (category_id)
    JOIN authors USING (author_id)
    LEFT JOIN section_agg ON courses.course_id = section_agg.course_id
WHERE
    courses.course_id = (SELECT course_id FROM target_course)
GROUP BY
    courses.course_id,
    courses.title,
    courses.description,
    courses.slug,
    courses.tags,
    courses.publish_status,
    courses.category_id,
    categories.name,
    courses.published_at,
    courses.author_id,
    authors.name,
    authors.slug,
    courses.visibility
`

type GetCourseBySlugParams struct {
	Courseslug string `json:"courseslug"`
	Authorslug string `json:"authorslug"`
}

type GetCourseBySlugRow struct {
	CourseID      pgtype.UUID        `json:"course_id"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Slug          string             `json:"slug"`
	Tags          []byte             `json:"tags"`
	PublishStatus string             `json:"publish_status"`
	CategoryID    pgtype.UUID        `json:"category_id"`
	CategoryName  string             `json:"category_name"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	AuthorID      pgtype.UUID        `json:"author_id"`
	AuthorName    string             `json:"author_name"`
	AuthorSlug    string             `json:"author_slug"`
	Visibility    string             `json:"visibility"`
	Sections      []byte             `json:"sections"`
}

func (q *Queries) GetCourseBySlug(ctx context.Context, arg GetCourseBySlugParams) (GetCourseBySlugRow, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, arg.Courseslug, arg.Authorslug)
	var i GetCourseBySlugRow
	err := row.Scan(
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.Slug,
		&i.Tags,
		&i.PublishStatus,
		&i.CategoryID,
		&i.CategoryName,
		&i.PublishedAt,
		&i.AuthorID,
		&i.AuthorName,
		&i.AuthorSlug,
		&i.Visibility,
		&i.Sections,
	)
	return i, err
}

const getCourseBySlugAndAuthorID = `-- name: GetCourseBySlugAndAuthorID :one
SELECT
    course_id
FROM
    courses
WHERE
    slug = $1
    AND author_id = $2 :: UUID
`

type GetCourseBySlugAndAuthorIDParams struct {
	Slug     string      `json:"slug"`
	Authorid pgtype.UUID `json:"authorid"`
}

func (q *Queries) GetCourseBySlugAndAuthorID(ctx context.Context, arg GetCourseBySlugAndAuthorIDParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCourseBySlugAndAuthorID, arg.Slug, arg.Authorid)
	var course_id pgtype.UUID
	err := row.Scan(&course_id)
	return course_id, err
}

const getCourses = `-- name: GetCourses :many
SELECT
    course_id AS "courseId",
    title
FROM
    courses
WHERE
    (
        courses.publish_status = 'published'
        AND courses.visibility IN ('public', 'paid')
    )
    AND (
        $1 :: uuid IS NULL
        OR course_id > $1
    )
    AND (
        NULLIF($2 :: text, '') IS NULL
        OR title LIKE '%' || $2 || '%'
        OR description LIKE '%' || $2 || '%'
    )
ORDER BY
    course_id
LIMIT
    $3
`

type GetCoursesParams struct {
	Cursor  pgtype.UUID `json:"cursor"`
	Keyword string      `json:"keyword"`
	Size    int32       `json:"size"`
}

type GetCoursesRow struct {
	CourseId pgtype.UUID `json:"courseId"`
	Title    string      `json:"title"`
}

func (q *Queries) GetCourses(ctx context.Context, arg GetCoursesParams) ([]GetCoursesRow, error) {
	rows, err := q.db.Query(ctx, getCourses, arg.Cursor, arg.Keyword, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCoursesRow{}
	for rows.Next() {
		var i GetCoursesRow
		if err := rows.Scan(&i.CourseId, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicDetail = `-- name: GetTopicDetail :one
SELECT
    courses.course_id AS "courseId",
    course_sections.course_section_id AS "sectionId",
    course_section_topics.course_section_topic_id as "topicId",
    course_section_topics.title,
    course_section_topics.description,
    course_section_topics.content
FROM
    course_section_topics
    JOIN course_sections USING (course_section_id)
    JOIN courses ON courses.course_id = course_sections.course_id
WHERE
    course_section_topic_id = $1 :: uuid
    AND course_sections.course_section_id = $2 :: uuid
    AND course_sections.course_id = $3 :: uuid
    AND (
        courses.publish_status = 'published'
        OR (
            $4 :: uuid IS NOT NULL
            AND courses.author_id = $4 :: uuid
        )
    )
`

type GetTopicDetailParams struct {
	TopicID   pgtype.UUID `json:"topic_id"`
	SectionID pgtype.UUID `json:"section_id"`
	CourseID  pgtype.UUID `json:"course_id"`
	UserID    pgtype.UUID `json:"user_id"`
}

type GetTopicDetailRow struct {
	CourseId    pgtype.UUID `json:"courseId"`
	SectionId   pgtype.UUID `json:"sectionId"`
	TopicId     pgtype.UUID `json:"topicId"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Content     string      `json:"content"`
}

func (q *Queries) GetTopicDetail(ctx context.Context, arg GetTopicDetailParams) (GetTopicDetailRow, error) {
	row := q.db.QueryRow(ctx, getTopicDetail,
		arg.TopicID,
		arg.SectionID,
		arg.CourseID,
		arg.UserID,
	)
	var i GetTopicDetailRow
	err := row.Scan(
		&i.CourseId,
		&i.SectionId,
		&i.TopicId,
		&i.Title,
		&i.Description,
		&i.Content,
	)
	return i, err
}

const insertAuthor = `-- name: InsertAuthor :exec
INSERT INTO authors (author_id, name, profile, slug)
VALUES ($1 :: UUID, $2, $3, $4)
`

type InsertAuthorParams struct {
	Authorid pgtype.UUID `json:"authorid"`
	Name     string      `json:"name"`
	Profile  string      `json:"profile"`
	Slug     string      `json:"slug"`
}

func (q *Queries) InsertAuthor(ctx context.Context, arg InsertAuthorParams) error {
	_, err := q.db.Exec(ctx, insertAuthor,
		arg.Authorid,
		arg.Name,
		arg.Profile,
		arg.Slug,
	)
	return err
}

const insertCategory = `-- name: InsertCategory :exec
INSERT INTO categories (category_id, name, path)
VALUES ($1 :: UUID, $2, $3 :: ltree)
`

type InsertCategoryParams struct {
	Categoryid pgtype.UUID `json:"categoryid"`
	Name       string      `json:"name"`
	Path       string      `json:"path"`
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) error {
	_, err := q.db.Exec(ctx, insertCategory, arg.Categoryid, arg.Name, arg.Path)
	return err
}

const insertCourse = `-- name: InsertCourse :exec
INSERT INTO courses (
    course_id, title, description, slug, tags, publish_status,
    category_id, published_at, author_id, visibility
) VALUES (
    $1 :: UUID, $2, $3, $4, $5 :: jsonb, $6,
    $7 :: UUID, $8, $9 :: UUID, $10
)
`

type InsertCourseParams struct {
	Courseid      pgtype.UUID        `json:"courseid"`
	Title         string             `json:"title"`
	Description   string             `json:"description"`
	Slug          string             `json:"slug"`
	Tags          []byte             `json:"tags"`
	Publishstatus string             `json:"publishstatus"`
	Categoryid    pgtype.UUID        `json:"categoryid"`
	Publishedat   pgtype.Timestamptz `json:"publishedat"`
	Authorid      pgtype.UUID        `json:"authorid"`
	Visibility    string             `json:"visibility"`
}

func (q *Queries) InsertCourse(ctx context.Context, arg InsertCourseParams) error {
	_, err := q.db.Exec(ctx, insertCourse,
		arg.Courseid,
		arg.Title,
		arg.Description,
		arg.Slug,
		arg.Tags,
		arg.Publishstatus,
		arg.Categoryid,
		arg.Publishedat,
		arg.Authorid,
		arg.Visibility,
	)
	return err
}

const insertCourseSection = `-- name: InsertCourseSection :exec
INSERT INTO course_sections (
    course_section_id, course_id, index, title, description
) VALUES (
    $1 :: UUID, $2 :: UUID, $3, $4, $5
)
`

type InsertCourseSectionParams struct {
	Coursesectionid pgtype.UUID `json:"coursesectionid"`
	Courseid        pgtype.UUID `json:"courseid"`
	Index           int16       `json:"index"`
	Title           string      `json:"title"`
	Description     string      `json:"description"`
}

func (q *Queries) InsertCourseSection(ctx context.Context, arg InsertCourseSectionParams) error {
	_, err := q.db.Exec(ctx, insertCourseSection,
		arg.Coursesectionid,
		arg.Courseid,
		arg.Index,
		arg.Title,
		arg.Description,
	)
	return err
}

const insertCourseSectionTopic = `-- name: InsertCourseSectionTopic :exec
INSERT INTO course_section_topics (
    course_section_topic_id, course_id, course_section_id,
    index, title, description, content
) VALUES (
    $1 :: UUID, $2 :: UUID, $3 :: UUID,
    $4, $5, $6, $7
)
`

type InsertCourseSectionTopicParams struct {
	Coursesectiontopicid pgtype.UUID `json:"coursesectiontopicid"`
	Courseid             pgtype.UUID `json:"courseid"`
	Coursesectionid      pgtype.UUID `json:"coursesectionid"`
	Index                int16       `json:"index"`
	Title                string      `json:"title"`
	Description          string      `json:"description"`
	Content              string      `json:"content"`
}

func (q *Queries) InsertCourseSectionTopic(ctx context.Context, arg InsertCourseSectionTopicParams) error {
	_, err := q.db.Exec(ctx, insertCourseSectionTopic,
		arg.Coursesectiontopicid,
		arg.Courseid,
		arg.Coursesectionid,
		arg.Index,
		arg.Title,
		arg.Description,
		arg.Content,
	)
	return err
}

const insertUserAuthor = `-- name: InsertUserAuthor :exec
INSERT INTO user_authors (user_id, author_id)
VALUES ($1 :: UUID, $2 :: UUID)
`

type InsertUserAuthorParams struct {
	Userid   pgtype.UUID `json:"userid"`
	Authorid pgtype.UUID `json:"authorid"`
}

func (q *Queries) InsertUserAuthor(ctx context.Context, arg InsertUserAuthorParams) error {
	_, err := q.db.Exec(ctx, insertUserAuthor, arg.Userid, arg.Authorid)
	return err
}

const listCategories = `-- name: ListCategories :many
SELECT
    category_id,
    name,
    path :: text AS path
FROM
    categories
ORDER BY
    path
`

type ListCategoriesRow struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Name       string      `json:"name"`
	Path       string      `json:"path"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCategoriesRow{}
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(&i.CategoryID, &i.Name, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
