// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEnrollmentsByUserID = `-- name: GetEnrollmentsByUserID :many
SELECT
    courses.course_id AS "courseId",
    courses.title
FROM
    user_topic_progresses
    JOIN course_section_topics ON user_topic_progresses.course_section_topic_id = course_section_topics.course_section_topic_id
    JOIN course_sections ON course_section_topics.course_section_id = course_sections.course_section_id
    JOIN courses ON course_sections.course_id = courses.course_id
WHERE
    user_topic_progresses.user_id = $1 :: uuid
GROUP BY
    courses.course_id, courses.title
ORDER BY
    MAX(user_topic_progresses._updated_at) DESC
`

type GetEnrollmentsByUserIDRow struct {
	CourseId pgtype.UUID `json:"courseId"`
	Title    string      `json:"title"`
}

func (q *Queries) GetEnrollmentsByUserID(ctx context.Context, userid pgtype.UUID) ([]GetEnrollmentsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getEnrollmentsByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnrollmentsByUserIDRow{}
	for rows.Next() {
		var i GetEnrollmentsByUserIDRow
		if err := rows.Scan(&i.CourseId, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
