// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCourseAuthorityById = `-- name: GetCourseAuthorityById :one
SELECT
    publish_status,
    author_id
FROM
    courses
WHERE
    courses.course_id = $1
`

type GetCourseAuthorityByIdRow struct {
	PublishStatus string      `json:"publish_status"`
	AuthorID      pgtype.UUID `json:"author_id"`
}

func (q *Queries) GetCourseAuthorityById(ctx context.Context, courseid pgtype.UUID) (GetCourseAuthorityByIdRow, error) {
	row := q.db.QueryRow(ctx, getCourseAuthorityById, courseid)
	var i GetCourseAuthorityByIdRow
	err := row.Scan(&i.PublishStatus, &i.AuthorID)
	return i, err
}

const getCourseStructureWithProgress = `-- name: GetCourseStructureWithProgress :one
WITH section_agg AS (
    SELECT
        sections.course_id,
        sections.course_section_id,
        sections.title,
        sections.index,
        COALESCE(
            jsonb_agg(
                jsonb_build_object(
                    'topicId',
                    topics.course_section_topic_id,
                    'title',
                    topics.title,
                    'status',
                    COALESCE(progresses.status, 'NOT_STARTED'),
                    'index',
                    topics.index
                )
                ORDER BY
                    topics.index
            ) FILTER (
                WHERE
                    topics.course_section_topic_id IS NOT NULL
            ),
            '[]' :: jsonb
        ) AS topics
    FROM
        course_sections AS sections
        LEFT JOIN course_section_topics AS topics ON sections.course_section_id = topics.course_section_id
        LEFT JOIN topic_progresses AS progresses ON progresses.user_id = $2
            AND progresses.course_id = sections.course_id
            AND progresses.course_section_topic_id = topics.course_section_topic_id
    WHERE
        sections.course_id = $1
    GROUP BY
        sections.course_id,
        sections.course_section_id,
        sections.index,
        sections.title
)
SELECT
    courses.course_id,
    courses.title,
    COALESCE(
        jsonb_agg(
            jsonb_build_object(
                'sectionId',
                section_agg.course_section_id,
                'title',
                section_agg.title,
                'index',
                section_agg.index,
                'topics',
                section_agg.topics
            )
            ORDER BY
                section_agg.index
        ) FILTER (
            WHERE
                section_agg.course_section_id IS NOT NULL
        ),
        '[]' :: jsonb
    ) :: jsonb AS sections
FROM
    courses
    LEFT JOIN section_agg ON courses.course_id = section_agg.course_id
WHERE
    courses.course_id = $1
GROUP BY
    courses.course_id
`

type GetCourseStructureWithProgressParams struct {
	Courseid pgtype.UUID `json:"courseid"`
	Userid   pgtype.UUID `json:"userid"`
}

type GetCourseStructureWithProgressRow struct {
	CourseID pgtype.UUID `json:"course_id"`
	Title    string      `json:"title"`
	Sections []byte      `json:"sections"`
}

func (q *Queries) GetCourseStructureWithProgress(ctx context.Context, arg GetCourseStructureWithProgressParams) (GetCourseStructureWithProgressRow, error) {
	row := q.db.QueryRow(ctx, getCourseStructureWithProgress, arg.Courseid, arg.Userid)
	var i GetCourseStructureWithProgressRow
	err := row.Scan(&i.CourseID, &i.Title, &i.Sections)
	return i, err
}

const getEnrollmentByUserIdAndCourseId = `-- name: GetEnrollmentByUserIdAndCourseId :one
SELECT
    user_id,
    course_id,
    enrolled_at
FROM
    enrollments
WHERE
    user_id = $1 :: uuid
    AND course_id = $2 :: uuid
`

type GetEnrollmentByUserIdAndCourseIdParams struct {
	Userid   pgtype.UUID `json:"userid"`
	Courseid pgtype.UUID `json:"courseid"`
}

type GetEnrollmentByUserIdAndCourseIdRow struct {
	UserID     pgtype.UUID        `json:"user_id"`
	CourseID   pgtype.UUID        `json:"course_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

func (q *Queries) GetEnrollmentByUserIdAndCourseId(ctx context.Context, arg GetEnrollmentByUserIdAndCourseIdParams) (GetEnrollmentByUserIdAndCourseIdRow, error) {
	row := q.db.QueryRow(ctx, getEnrollmentByUserIdAndCourseId, arg.Userid, arg.Courseid)
	var i GetEnrollmentByUserIdAndCourseIdRow
	err := row.Scan(&i.UserID, &i.CourseID, &i.EnrolledAt)
	return i, err
}

const getEnrollmentsByUserID = `-- name: GetEnrollmentsByUserID :many
SELECT
    courses.course_id AS "courseId",
    courses.title
FROM
    enrollments
    JOIN courses ON enrollments.course_id = courses.course_id
    LEFT JOIN topic_progresses ON topic_progresses.user_id = enrollments.user_id
        AND topic_progresses.course_id = enrollments.course_id
WHERE
    enrollments.user_id = $1 :: uuid
GROUP BY
    courses.course_id,
    courses.title,
    enrollments.enrolled_at
ORDER BY
    COALESCE(MAX(topic_progresses._updated_at), enrollments.enrolled_at) DESC
`

type GetEnrollmentsByUserIDRow struct {
	CourseId pgtype.UUID `json:"courseId"`
	Title    string      `json:"title"`
}

func (q *Queries) GetEnrollmentsByUserID(ctx context.Context, userid pgtype.UUID) ([]GetEnrollmentsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getEnrollmentsByUserID, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnrollmentsByUserIDRow{}
	for rows.Next() {
		var i GetEnrollmentsByUserIDRow
		if err := rows.Scan(&i.CourseId, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopicProgressesByUserIdAndCourseId = `-- name: GetTopicProgressesByUserIdAndCourseId :many
SELECT
    course_section_topic_id,
    status
FROM
    topic_progresses
WHERE
    user_id = $1 :: uuid
    AND course_id = $2 :: uuid
`

type GetTopicProgressesByUserIdAndCourseIdParams struct {
	Userid   pgtype.UUID `json:"userid"`
	Courseid pgtype.UUID `json:"courseid"`
}

type GetTopicProgressesByUserIdAndCourseIdRow struct {
	CourseSectionTopicID pgtype.UUID `json:"course_section_topic_id"`
	Status               string      `json:"status"`
}

func (q *Queries) GetTopicProgressesByUserIdAndCourseId(ctx context.Context, arg GetTopicProgressesByUserIdAndCourseIdParams) ([]GetTopicProgressesByUserIdAndCourseIdRow, error) {
	rows, err := q.db.Query(ctx, getTopicProgressesByUserIdAndCourseId, arg.Userid, arg.Courseid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopicProgressesByUserIdAndCourseIdRow{}
	for rows.Next() {
		var i GetTopicProgressesByUserIdAndCourseIdRow
		if err := rows.Scan(&i.CourseSectionTopicID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEnrollment = `-- name: InsertEnrollment :exec
INSERT INTO
    enrollments (
        user_id,
        course_id,
        enrolled_at
    )
VALUES
    (
        $1 :: uuid,
        $2 :: uuid,
        $3
    )
`

type InsertEnrollmentParams struct {
	Userid     pgtype.UUID        `json:"userid"`
	Courseid   pgtype.UUID        `json:"courseid"`
	Enrolledat pgtype.Timestamptz `json:"enrolledat"`
}

func (q *Queries) InsertEnrollment(ctx context.Context, arg InsertEnrollmentParams) error {
	_, err := q.db.Exec(ctx, insertEnrollment, arg.Userid, arg.Courseid, arg.Enrolledat)
	return err
}

const upsertTopicProgress = `-- name: UpsertTopicProgress :exec
INSERT INTO
    topic_progresses (
        user_id,
        course_id,
        course_section_topic_id,
        status
    )
VALUES
    (
        $1 :: uuid,
        $2 :: uuid,
        $3 :: uuid,
        $4
    ) ON CONFLICT (user_id, course_id, course_section_topic_id) DO
UPDATE
SET
    status = EXCLUDED.status
`

type UpsertTopicProgressParams struct {
	Userid               pgtype.UUID `json:"userid"`
	Courseid             pgtype.UUID `json:"courseid"`
	Coursesectiontopicid pgtype.UUID `json:"coursesectiontopicid"`
	Status               string      `json:"status"`
}

func (q *Queries) UpsertTopicProgress(ctx context.Context, arg UpsertTopicProgressParams) error {
	_, err := q.db.Exec(ctx, upsertTopicProgress,
		arg.Userid,
		arg.Courseid,
		arg.Coursesectiontopicid,
		arg.Status,
	)
	return err
}
