// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountApiKeyByUserID(ctx context.Context, userid pgtype.UUID) (int64, error)
	GetCourseById(ctx context.Context, courseid pgtype.UUID) (GetCourseByIdRow, error)
	GetCourses(ctx context.Context, arg GetCoursesParams) ([]GetCoursesRow, error)
	GetEnrollmentsByUserID(ctx context.Context, userid pgtype.UUID) ([]GetEnrollmentsByUserIDRow, error)
	GetProgressByUserIdAndCourseId(ctx context.Context, arg GetProgressByUserIdAndCourseIdParams) ([]GetProgressByUserIdAndCourseIdRow, error)
	GetTopicDetail(ctx context.Context, arg GetTopicDetailParams) (GetTopicDetailRow, error)
	GetUser(ctx context.Context, userid pgtype.UUID) (GetUserRow, error)
	InsertApiKey(ctx context.Context, arg InsertApiKeyParams) error
	ListApiKeysByUserID(ctx context.Context, userid pgtype.UUID) ([]ListApiKeysByUserIDRow, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertProgress(ctx context.Context, arg UpsertProgressParams) error
}

var _ Querier = (*Queries)(nil)
