// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	GetCourses(ctx context.Context, arg GetCoursesParams) ([]GetCoursesRow, error)
}

var _ Querier = (*Queries)(nil)
